### ISSUE TITLE
Deprecated option vendorSha256

### ISSUE THREAD

**Issue by W-Y-R** [schizofox/schizofox#82] opened 2024-02-15 19:31 UTC
I've recently started using Schizofox, and since then I'm getting ```warning: `vendorSha256` is deprecated. Use `vendorHash` instead```. Could you fix this, please?

**Comment by NotAShelf** [comment] 2024-02-16 06:38
I'm not very sure where this is coming from. We don't use `vendorSha256` in Schizofox at all. I've bumped all inputs to latest, but the message still pops up - maybe one of our dependencies (not that there's many) is using it? I'll investigate further.

**Comment by Saturn745** [comment] 2024-02-21 21:41
Was looking into NixOS sandboxing myself and found NixPak which eventually led me here. The cause of "warning: `vendorSha256` is deprecated. Use `vendorHash` instead" is NixPak [here](https://github.com/nixpak/nixpak/blob/903020fdc3e77e896404a2888f4b896638400854/launcher/default.nix#L11)

**Comment by NotAShelf** [comment] 2024-02-21 22:04
Appreciated, thanks for letting me know. I'll make a PR to Nixpak tomorrow.

**Comment by NotAShelf** [comment] 2024-02-22 09:34
I've opened a PR at https://github.com/nixpak/nixpak/pull/59. Those annoyed by the errors can override Schizofox's nixpak input with `github:schizofox/nixpak` until the the MR is merged.

**Closed** 2024-02-22 11:02 UTC
